[package]
name = "discord_tts_bot"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
panic = "abort"
debug = 2

[dependencies]
serde = "1"
regex = "1"
toml = "0.8"
rand = "0.8"
anyhow = "1"
sha2 = "0.10"
indexmap = "2"
tracing = "0.1"
gettext = "0.4"
linkify = "0.10"
strsim = "0.10"
sysinfo = "0.29"
num-format = "0.4"
itertools = "0.12"
parking_lot = "0.12"
const_format = "0.2"
strum_macros = "0.25"
arrayvec = "0.7.4"
bitflags = "2.4.1"
paste = "1.0.14"
typesize = { version = "0.1.1", path = "../rust-libs/typesize" }

[dependencies.symphonia]
features = ["mp3", "ogg", "wav", "pcm"]
default-features = false
version = "0.5.3"

[dependencies.sqlx]
version = "0.7"
default-features = false
features = ["macros", "postgres", "runtime-tokio-rustls"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls"]

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread", "signal", "parking_lot"]

[dependencies.dashmap]
version = "5"
default-features = false

[dependencies.serenity_feature_only]
path = "../rust-libs/serenity"
features = ["unstable_discord_api", "typesize"]
default-features = false
package = "serenity"

[dependencies.poise]
git = "https://github.com/serenity-rs/poise"
features = ["cache"]
branch = "serenity-next"

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
features = ["builtin-queue"]
branch = "next"

[patch.crates-io]
serenity = { path = "../rust-libs/serenity" }
serenity-voice-model = { path = "../rust-libs/serenity/voice-model" }

[patch."https://github.com/serenity-rs/serenity"]
serenity = { path = "../rust-libs/serenity" }
serenity-voice-model = { path = "../rust-libs/serenity/voice-model" }
