services:
    bot:
        build: .
        volumes:
            - type: bind
            source: ./config.ini
            target: /config.ini
            - type: bind
            source: ${GOOGLE_APPLICATION_CREDENTIALS}
            target: /gcp.json

        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=gcp.json

        command: ["./wait-for-it.sh", "postgres:5432", "cache:6379", "--strict", "--", "python3", "-u", "main.py"]
    database:
        image: postgres:13
        expose: [5432]
        environment: 
            POSTGRES_USER: tts
            POSTGRES_PASSWORD: tts_password
    cache:
        image: eqalpha/keydb:latest
        expose: [6379]
        volumes:
            - type: bind
              source: ./keydb.conf
              target: /etc/keydb/keydb.conf
