services:
    bot:
        build: .
        volumes:
        -   type: bind
            source: ./config.ini
            target: /config.ini,
        command: ["./wait-for-it.sh", "postgres:5432", "cache:6379", "--strict", "--", "python3", "-u" "bot.py"]
        depends_on: [database, cache]
        restart: always
    database:
        image: postgres:13
        expose: [5432]
        environment: 
            POSTGRES_USER: tts
            POSTGRES_PASSWORD: tts_password
    cache:
        image: eqalpha/keydb:latest
        expose: [6379]
        volumes:
            - type: bind
              source: ./keydb.conf
              target: /etc/keydb/keydb.conf
