[package]
name = "tts_activity_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
thiserror = "1"
small-fixed-array = "0.4.4"

reqwest.workspace = true
tracing.workspace = true
tokio.workspace = true

tts_core = { path = "../tts_core" }
